### ISSUE TITLE
Wrong spacing after number before preposition

### ISSUE THREAD

**Issue by olsak** [michal-h21/luavlna#12]
Try this using `luatex`:

```
\input luavlna

1.3\qquad V tomto bodu.

Porovnejte: \preventsingleoff

1.3\qquad V tomto bodu.

\bye
```
The first line has wrong spacing. The `\qquad` is replaced by normal space. I discovered this problem when my title of subsection started with V.

**Comment by michal-h21** [comment]
Thanks for the report. I've changed the code to test if glue has the `spaceskip` subtype: 5e976b0. It seems to help in this case.
