### ISSUE TITLE
Prevent line breaks after `a` in Slovak, be more permissive in Czech

### ISSUE THREAD

**Issue by Witiko** [michal-h21/luavlna#13]
I noticed that the package allows line breaks after the letter `a`, which seems to be an error of omission:

https://github.com/michal-h21/luavlna/blob/db342d10aee09dcea5db021976cb91a19c6e3624/luavlna.sty#L53-L54
https://github.com/michal-h21/luavlna/blob/db342d10aee09dcea5db021976cb91a19c6e3624/luavlna-doc.tex#L177-L178

Furthermore, as far as I know, Czech typographic rules only forbid line breaks after unsyllabic prepositions, i.e. the defaults seem too prohibitive. Regardless, here are the defaults that I use in my documents:

``` tex
 \singlechars{czech}{VvSsZzKk} 
 \singlechars{slovak}{AaIiVvOoUuSsZzKk} 
```

**Comment by michal-h21** [comment]
Thanks for the report. I've added your settings to `luavlna.sty` and `luavlna.tex`.

**Comment by Witiko** [comment]
Thanks, happy to help!

**Comment by Witiko** [comment]
I double-checked the ČSN 01 6910:2014 norm.

![scrot01](https://user-images.githubusercontent.com/603082/236535737-a46025d3-ec10-4fae-99f5-6ae2882f86ec.jpg)

![scrot02](https://user-images.githubusercontent.com/603082/236535753-664b26c0-e8b4-4436-b878-b822be9899f8.jpg)

It turns out I was wrong and the correct setting for Czech is the same as for Slovak:

```tex
\singlechars{czech}{AaIiVvOoUuSsZzKk}
```

I am sorry about the confusion. It seems to me as though this rule has been updated since the 2007 norm, but I cannot check at the moment.

**Comment by michal-h21** [comment]
I was always convinced that at least `a` was allowed at the end of a line. Thanks for finding of this norm. I've updated the code accordingly.
