### ISSUE TITLE
Unwanted substitutions

### ISSUE THREAD

**Issue by lahwaacz** [michal-h21/luavlna#2]
If I write `$k \in \mathbb N$`, luavlna tranforms it into `$k \in~\mathbb N$`, which is rendered with asymmetric spacing most of the time. How can I restrict substitutions only to plain text?

**Comment by michal-h21** [comment]
You are right, thanks for report. It should be fixed in the last commit.

**Comment by lahwaacz** [comment]
Indeed, thanks!

Though I have another false positive, this time in plain text: if a sentence ends with an all-caps word like HTML, USA or ABCDEFGHIJKLMNOPQRSTUVWXYZ, then the space following the full stop is non-breaking.

**Comment by michal-h21** [comment]
It should be fixed now, I hope.

**Comment by lahwaacz** [comment]
Thanks!
