### ISSUE TITLE
Potential feature: splithyphens

### ISSUE THREAD

**Issue by jspitz** [michal-h21/luavlna#4]
I was wondering whether it is possible with lua to implement the splithyphens feature for Czech. I.e., the replication of a hyphen char at the beginning of a line following an hyphenation.

Babel-czech implements this in a rather tricky and fragile way (making `-` active), which conflicts with many packages that require `-` to be non-active (booktabs, array). I think XeTeX has no means to to that, as the XeTeXinterchar mechanism chimes in before paragraphs are broken. But maybe LuaTeX has?

As this package addresses a Czech typesetting problem, it might be a feature to add.

If not, feel free to close this ticket.

**Comment by michal-h21** [comment]
@jspitz that's a good idea. I've just added the support for this feature. It is enabled by default for Czech. I've used the `hyphenate` callback, so it shouldn't collide with TeX macros. It also seems to work correctly for math.

**Comment by jspitz** [comment]
Great, thanks!

There is another potential feature to ponder about: Apparently, in Czech typography, hyphenation at page boundary should be omitted. This seems to be more tricky, but possible with LuaTeX: https://tex.stackexchange.com/a/493060/19291

**Comment by michal-h21** [comment]
Ah, this one seems to be much trickier. I think `\brokenpenalty=10000` should work too?

**Comment by jspitz** [comment]
`\brokenpenalty` only works sufficiently in specific cases, Since it it only applied when paragraphs are already broken, it results in underfull pages and other undesirable effects. The lua solution linked to above seems to be more effective, as it chimes in before paragraphs are being broken.

**Comment by jspitz** [comment]
BTW as I understand from babel-slovak, splithyphens should also be active by default for Slovak.

**Comment by jspitz** [comment]
I now tested the feature with the new luavlna release. Alas, I cannot get it to work with polyglossia:
```tex
% !TeX TS-program = lualatex
\documentclass{article}
\usepackage{polyglossia}
\setmainlanguage{czech}
%\usepackage[czech]{babel}
\usepackage{luavlna}
\begin{document}
	Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
	Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
	Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
	Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
	Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
	Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
	Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer Sedlec-Prčice, modro-zelený, překladatel-tlumočník, kuchař-číšník, propan-butan,
	Otýlie Sklenářová-Malá, František Jílek-Oberpfalcer 
\end{document}
```

![image](https://user-images.githubusercontent.com/4538783/67754454-ca41d200-fa36-11e9-8816-dc37930ce1ff.png)


Babel works. Also, the vlna feature does work with polyglossia.

**Comment by michal-h21** [comment]
Thanks for the report, you are right. I've forgot that Poyglossia needs a special treatment. It should work now.

I've also found that the split hyphen option doesn't work with CSplain. It seems that the `hyphenate` LuaTeX callback is not called at all. Which is strange, but I cannot find why.

**Comment by jspitz** [comment]
Thanks. I can confirm it works now.,

**Comment by michal-h21** [comment]
@jspitz great, I've just posted an update to CTAN.

**Comment by jspitz** [comment]
Thank you. Just for the record, the next version of `polyglossia` will automatically load `luavlna` for Czech and Slovak with LuaTeX with `vlna` and `splithyphens` preset (and language options to unset each feature)

**Comment by michal-h21** [comment]
Oh, that's great to hear, thanks :)
