### ISSUE TITLE
Spurious space in definition

### ISSUE THREAD

**Issue by jspitz** [michal-h21/luavlna#5]
There is a spurious space caused by unprotected line end in this definition:

```tex
\def\enablesplithyphens#1{%
  \ifcsname l@#1\endcsname%
  \typeout{set lang #1, \the\csname l@#1\endcsname}
    \directlua{enable_split_hyphens("\the\csname l@#1\endcsname")}%
  \fi%
}
```

This needs to be

```tex
  \typeout{set lang #1, \the\csname l@#1\endcsname}%
```

See https://tex.stackexchange.com/questions/547477/

**Comment by michal-h21** [comment]
Wow, I didn't even know that Luavlna is used in Polyglossia. Thanks for the report. I will upload fix to CTAN as soon as possible.

**Comment by jspitz** [comment]
> Wow, I didn't even know that Luavlna is used in Polyglossia. 

Sure you did ;-) https://github.com/michal-h21/luavlna/issues/4#issuecomment-547498492

> Thanks for the report. I will upload fix to CTAN as soon as possible.

Thanks!

**Comment by michal-h21** [comment]
@jspitz ah, I can have really bad memory sometimes :)
