### ISSUE TITLE
wrong language ID detection

### ISSUE THREAD

**Issue by mbudaj** [michal-h21/luavlna#6]
The function `load_lang_dat` finds the language ID/name pairs by parsing the file language.dat. On my system (TeXlive 2020, LuaTeX 1.12.0) it gets most IDs off by 2 compared to IDs returned by \the\language itself (e.g. 12 instead of 10 for 'czech').

The reason is that the file language.dat contains two language definitions (dumylang and nohyphenation) right after the definition of English, but these two languages are not used by luatex at all. Hence the offset by 2 for all subsequent languages.

There are two other files in the same directory where language.dat is located. They should be more reliable for the purpose of getting language ID, and in my case they don't contain the problematic dumylang and nohyphenation:
- language.def, which is actually used by etex.src to load language definitions into luatex (so it's the the most reliable source)
- language.dat.lua, which has the advantage that it returns a lua table directly

Actually, does the package need also ID→name mapping? If not, then instead of parsing, just calling something like `\csname lang@#1\endcsname` where `#1` is the language name could be sufficient to get the ID.

**Comment by michal-h21** [comment]
Sorry for the late reply, I somehow missed it. Do you have a `mwe`? The following example works for me with `luatex`  and TL 2020:

```
\input ucode
\uselanguage{czech}
\input luavlna
\preventsingledebugon
\input luaotfload.sty
\font\hello={name:Linux Libertine O:+rlig;+clig;+liga;+tlig} at 12pt
\hsize=3in
\hello
Příliš žluťoučký kůň úpěl ďábelské ódy.
Text s krátkými souhláskami a samohláskami i dalšími jevy
z nabídky možností (v textu možnými).
I začátek odstavce je třeba řešit, i když výskyt zalomení
není pravděpodobný.
Co třeba í znaky š diakritikou?
Různé možnosti [v závorkách <i jiných znacích
Podpora iniciál a titulů: M. J. Hegel, Ing. Běháková, Ph.D., Ž. Zíbrt.

\bye

```

**Comment by mbudaj** [comment]
Here is the result produced from your example: [test.pdf](https://github.com/michal-h21/luavlna/files/5791723/test.pdf). 

I get the "expected" result when I use `\uselanguage{irish}` instead of `\uselanguage{czech}`, as Irish is ordered two positions before Czech on my system, compensating for the offset-by-two: [test-irish.pdf](https://github.com/michal-h21/luavlna/files/5791761/test-irish.pdf).

**Comment by michal-h21** [comment]
I see. This is different result than on my system. In this case you can try to redefine the `\setsinglechars` command to use `\lang@#`:

```
\input ucode
\uselanguage{czech}
\input luavlna

\def\singlechars#1#2{%
  \ifcsname lang@#1\endcsname%
    \expandafter\directlua\expandafter{set_singlechars("\the\csname lang@#1\endcsname","#2")}%
  \fi%
}
\singlechars{czech}{AIiVvOoUuSsZzKk}

\preventsingledebugon
\input luaotfload.sty
\font\hello={name:Linux Libertine O:+rlig;+clig;+liga;+tlig} at 12pt
\hsize=3in
\hello
Příliš žluťoučký kůň úpěl ďábelské ódy.
Text s krátkými souhláskami a samohláskami i dalšími jevy
z nabídky možností (v textu možnými).
I začátek odstavce je třeba řešit, i když výskyt zalomení
není pravděpodobný.
\bye

```

**Comment by mbudaj** [comment]
This works, thanks.

**Comment by michal-h21** [comment]
That's great!
