### ISSUE TITLE
\compoundinitials seem to do nothing

### ISSUE THREAD

**Issue by olsak** [michal-h21/luavlna#7]
I tried to implement your luavlna in my OpTeX format, see [vlna.opm](https://github.com/olsak/OpTeX/blob/master/optex/pkg/vlna.opm). Bu I have found two problems. One mentioned here, second in the next issue.

I didn't understand the doc or there is something wrong in \compoundinitials implememtation. I tried:

```
\input ucode
\uselanguage{czech}
\input luavlna
\preventsingledebugon

Text s textem. J. Kubina, Ch. Borner. 
```
and run luatex. I suppose a purple rectangle at the space between Ch. and B but it isn't here.

**Comment by michal-h21** [comment]
Thanks for the report. You are right, it seems that `\comoundinitials` don't work at all. It almost looks like I forgot to add the support, because there was no code that would look at the table where compound initials are stored. It should work in the development version now.

**Comment by olsak** [comment]
It works. It was less important issue because I don't know any Czech first name which begins by Ch. But this feature was mentioned in the documentation...

**Comment by michal-h21** [comment]
Yes, it was a serious omission that it didn't work. Thanks for the report.
