### ISSUE TITLE
LuaTeX hangs when \hbox{-} presents in a paragraph

### ISSUE THREAD

**Issue by olsak** [michal-h21/luavlna#8]
If `\hbox{-}` exists in the paragraph which must to be broken into lines and `\enablesplithyphens` is active in the current language then LuaTeX hangs in a infinite loop. We must to kill it by system tools. You can try:
```
\input ucode
\uselanguage{czech}
\input luavlna
\preventsingledebugon

aha \hbox{-} ouha.
\bye
```
and run LuaTeX.

**Comment by michal-h21** [comment]
Thanks for the report. The split hyphens now checks if the next node is glyph, it doesn't execute the code otherwise. It seems to fix this issue.

**Comment by olsak** [comment]
It works, but I don't understand why. IMHO it was connected to the fact, that next node is nil inside the contents of the `\hbox`. The penalties are not added inside `\hbox` (this is OK), so I was surprised why split-hyphens do something in nested lists of nodes.

**Comment by michal-h21** [comment]
The hyphens are handled in `hyphenate` callback, which  is executed for each list, including `\hbox`. It seems that the penalty inserting code caused infinite loop when hyphen was the last node in list. It shouldn't happen anymore.
